apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-main-broker
  namespace: database
  labels:
    strimzi.io/cluster: kafka-main
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 5Gi
    class: efs-mysql
    deleteClaim: true
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-main
  namespace: database
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 25m
          memory: 400Mi
        limits:
          memory: 600Mi
    userOperator:
      resources:
        requests:
          cpu: 25m
          memory: 350Mi
        limits:
          memory: 500Mi
