finalizers:
  - percona.com/delete-psmdb-pods-in-order

nameOverride: mongodb-main
fullnameOverride: mongodb-main

crVersion: 1.22.0
pause: false
unmanaged: false

unsafeFlags:
  tls: false
  replsetSize: false
  mongosSize: false
  terminationGracePeriod: false
  backupIfUnhealthy: false

enableVolumeExpansion: true

image:
  repository: percona/percona-server-mongodb
  tag: 8.0.19-7

imagePullPolicy: IfNotPresent

logcollector:
  enabled: false

pmm:
  enabled: false

replsets:
  rs0:
    name: rs0
    size: 3
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 900Mi
      limits:
        cpu: 1
        memory: 1500Mi
    volumeSpec:
      pvc:
        storageClassName: gp3-encrypted
        resources:
          requests:
            storage: 5Gi

sharding:
  enabled: false

backup:
  enabled: false

users: []
