apiVersion: v1
data:
  rootPassword: U25vcmUtcmVib2Iyc3RhaXItQ3VzaA==
  rootUser: cGxhdGZvcm1fdXNlcg==
kind: Secret
metadata:
  creationTimestamp: "2026-03-06T15:51:54Z"
  name: mysql-main-user
  namespace: database
  resourceVersion: "66144"
  uid: 186e1f42-bd65-444d-80e0-f8dca132bffa
type: Opaque
