apiVersion: v1
kind: Secret
metadata:
  name: pim-partners-bundling-secret
  namespace: pim-partners-bundling
  labels:
    app.kubernetes.io/name: pim-partners-bundling
    app.kubernetes.io/instance: pim-partners
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  PARTNERS_APP_CI_ENVIRONMENT: "production"
  PARTNERS_APP_BASE_URL: "https://partners.electgo.com/app/"
  PUNCHOUT_CI_ENVIRONMENT: "production"
  PUNCHOUT_BASE_URL: "https://partners.electgo.com/punchoutclient"
  PIM_MASTER_URL: "https://pim.electgo.com"
