apiVersion: v1
kind: Secret
metadata:
  name: pim-partners-secret
  namespace: pim-partners
  labels:
    app.kubernetes.io/name: pim-partners
    app.kubernetes.io/instance: pim-partners
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  CI_ENVIRONMENT: "development"
  app.baseURL: "CHANGE_ME_DEV_APP_BASEURL"
