apiVersion: v1
kind: Secret
metadata:
  name: pim-partners-secret
  namespace: pim-partners-prod
  labels:
    app.kubernetes.io/name: pim-partners
    app.kubernetes.io/instance: pim-partners-prod
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  CI_ENVIRONMENT: "production"
  app.baseURL: "CHANGE_ME_PROD_APP_BASEURL"
