apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pim-sku-finder
  namespace: argocd
spec:
  project: product
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: pim-sku-finder-secret
      namespace: pim-sku-finder
      jsonPointers:
        - /data
        - /stringData
  source:
    repoURL: https://github.com/electgo/pim-sku-finder
    targetRevision: main
    path: deployments/helm
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pim-sku-finder
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
