apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter-sidecar
  namespace: database
  labels:
    release: kps
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: postgres-main-pg-db
      postgres-operator.crunchydata.com/data: postgres
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role
          targetLabel: role
        - sourceLabels:
            - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance_set
          targetLabel: instance_set
