apiVersion: v1
kind: Secret
metadata:
  name: pim-chatbot-env
  namespace: pim-chatbot-dev
  labels:
    app.kubernetes.io/name: pim-chatbot
    app.kubernetes.io/instance: pim-chatbot-dev
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  .env: |
    CI_ENVIRONMENT = "development"
    app.baseURL = "https://pim-chatbot.dev.electgo.com"

    bot.runner =
    bot.runner.apikey =
    chatbot.sender =

    gpt.apikey = CHANGE_ME_DEV_GPT_APIKEY
    gpt.apikey2 =
    gpt.customapikey =
    gpt.vectorstore.qna =
    gpt.vectorstore.product =

    n8n.trainer.main =

    deploy.secretkey = CHANGE_ME_DEV_DEPLOY_SECRETKEY

    bucketupload.accesskey = CHANGE_ME_DEV_BUCKETUPLOAD_ACCESSKEY
    bucketupload.endpoint = bucketupload.electgo.com

    elastic.egchatbot.default = http://elasticsearch-main-instances.database.svc.cluster.local:9200/egchatbot_sg_dev
    elastic.egchatbot.indo = http://elasticsearch-main-instances.database.svc.cluster.local:9200/egchatbot_id_dev
    elastic.egchatbot.staging = http://elasticsearch-main-instances.database.svc.cluster.local:9200/egchatbot_staging_sg_dev
    elastic.egchatbot.staging_id = http://elasticsearch-main-instances.database.svc.cluster.local:9200/egchatbot_staging_id_dev
    elastic.egchatbot.user = egchatbot_dev
    elastic.egchatbot.password = AnEcDbyONMCYA0EUf2tzkBlU

    database.default.hostname = mysql-main-instances
    database.default.database = pim_chatbot_dev
    database.default.username = pim_dev
    database.default.password = qwYPGtKpvBAPHLOsYdMpplxl
    database.default.DBDriver = MySQLi
    database.default.DBPrefix =
    database.default.port = 3306

    database.pim_master.hostname = mysql-main-instances
    database.pim_master.database = pim_master_dev
    database.pim_master.username = pim_dev
    database.pim_master.password = qwYPGtKpvBAPHLOsYdMpplxl
    database.pim_master.DBDriver = MySQLi
    database.pim_master.DBPrefix =
    database.pim_master.port = 3306

    database.pim_indo.hostname = mysql-main-instances
    database.pim_indo.database = pim_indo_dev
    database.pim_indo.username = pim_dev
    database.pim_indo.password = qwYPGtKpvBAPHLOsYdMpplxl
    database.pim_indo.DBDriver = MySQLi
    database.pim_indo.DBPrefix =
    database.pim_indo.port = 3306

    database.pim_staging.hostname = mysql-main-instances
    database.pim_staging.database = pim_staging_dev
    database.pim_staging.username = pim_dev
    database.pim_staging.password = qwYPGtKpvBAPHLOsYdMpplxl
    database.pim_staging.DBDriver = MySQLi
    database.pim_staging.DBPrefix =
    database.pim_staging.port = 3306

    database.pim_staging_id.hostname = mysql-main-instances
    database.pim_staging_id.database = pim_staging_id_dev
    database.pim_staging_id.username = pim_dev
    database.pim_staging_id.password = qwYPGtKpvBAPHLOsYdMpplxl
    database.pim_staging_id.DBDriver = MySQLi
    database.pim_staging_id.DBPrefix =
    database.pim_staging_id.port = 3306
