apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller-prod
  namespace: argocd
spec:
  destination:
    name: production
    namespace: arc-systems
  project: platform
  source:
    chart: gha-runner-scale-set-controller
    helm:
      releaseName: arc
      skipCrds: true
      values: |
        replicaCount: 1
        nodeSelector:
          kubernetes.io/arch: arm64
          kubernetes.io/os: linux
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
        flags:
          logLevel: info
          logFormat: json
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
