apiVersion: v1
kind: Secret
metadata:
  name: pim-partners-punchout-client-secret
  namespace: pim-partners-punchout-client-prod
  labels:
    app.kubernetes.io/name: pim-partners-punchout-client
    app.kubernetes.io/instance: pim-partners-punchout-client-prod
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  CI_ENVIRONMENT: "production"
  app.baseURL: "https://partners.electgo.com/punchoutclient"
  database.default.hostname: "mysql-main-instances"
  database.default.database: "punchout"
  database.default.username: "dbmasteruser"
  database.default.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.default.DBDriver: "MySQLi"
  database.default.DBPrefix: ""
  database.default.port: "3306"
  database.pim.hostname: "mysql-main-instances"
  database.pim.database: "pim_master"
  database.pim.username: "dbmasteruser"
  database.pim.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.pim.DBDriver: "MySQLi"
  database.pim.DBPrefix: ""
  database.pim.port: "3306"
