apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ElectGo2026Mysql"
  MYSQL_DATABASE: "app"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "ElectGo2026Postgres"
  POSTGRES_DB: "app"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "dev-mongo-2026-secure"
  MONGO_INITDB_DATABASE: "app"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: database
type: Opaque
stringData:
  elastic-password: "dev-elastic-2026-secure"
