apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: electgo-be-point-reward-dev
  namespace: argocd
spec:
  project: marketplace
  source:
    repoURL: https://github.com/electgo/electgo-be-point-reward
    targetRevision: develop
    path: helm/electgo-be-point-reward
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: replicaCount
          value: "1"
        - name: secret.create
          value: "true"
        - name: imageCredentials.create
          value: "false"
        - name: env.secret.MONGODB_URI
          value: "mongodb://sharedops:__REDACTED_SHAREDOPS_PASSWORD__@mongodb.database.svc.cluster.local:27017/electgo?authSource=admin"
  destination:
    server: https://10.20.17.100:6443
    namespace: electgo-be-point-reward
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
