apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: database
type: Opaque
stringData:
  # MySQL root password untuk cluster baru (both keys needed)
  root-password: "rootpass"
  rootPassword: "rootpass"
  
  # Application user (replicate dari Lightsail)
  app-user: "dbmasteruser"
  app-password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  
  # Lightsail credentials untuk migration
  lightsail-user: "dbmasteruser"
  lightsail-password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  lightsail-endpoint: "ls-353e18d21571d615edfc7a67900d5c6eb53d58fb.clc58bmqhdz9.ap-southeast-1.rds.amazonaws.com"
