apiVersion: v1
kind: Secret
metadata:
  name: postgres-lightsail-credentials
  namespace: database
type: Opaque
stringData:
  host: "ls-d7f0eb15926c1e43e66aa3386c30ac683e54d2f4.clc58bmqhdz9.ap-southeast-1.rds.amazonaws.com"
  port: "5432"
  username: "dbmasteruser"
  password: "wB{7eD=biLaN_{XTTB6gPL~^*J]90gN|"
  databases: "dbmaster chatbot_ev electgo_chatbot electgo_chatbot_staging electgo_tools electgo_tools_staging etools_chatbot_be etools_chatbot_be_staging n8n_production"
