apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: database
type: Opaque
stringData:
  password: ElectGoRedis7Dev2026!
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-lightsail-credentials
  namespace: database
type: Opaque
stringData:
  host: "52.74.252.4"
  port: "6379"
  password: "36xU2FvrrW5rqRlJ"
