apiVersion: v1
kind: Secret
metadata:
  name: pim-partners-app-secret
  namespace: pim-partners-app-prod
  labels:
    app.kubernetes.io/name: pim-partners-app
    app.kubernetes.io/instance: pim-partners-app-prod
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  CI_ENVIRONMENT: "production"
  app.baseURL: "CHANGE_ME_PROD_APP_BASEURL"
  database.default.hostname: "mysql-main-instances"
  database.default.database: "pim_master"
  database.default.username: "dbmasteruser"
  database.default.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.default.DBDriver: "MySQLi"
  database.default.DBPrefix: ""
  database.default.port: "3306"
  database.staging.hostname: "mysql-main-instances"
  database.staging.database: "pim_staging"
  database.staging.username: "dbmasteruser"
  database.staging.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.staging.DBDriver: "MySQLi"
  database.staging.DBPrefix: ""
  database.staging.port: "3306"
  database.punchout.hostname: "mysql-main-instances"
  database.punchout.database: "punchout"
  database.punchout.username: "dbmasteruser"
  database.punchout.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.punchout.DBDriver: "MySQLi"
  database.punchout.DBPrefix: ""
  database.punchout.port: "3306"
  database.chatbot.hostname: "mysql-main-instances"
  database.chatbot.database: "pim_chatbot"
  database.chatbot.username: "dbmasteruser"
  database.chatbot.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.chatbot.DBDriver: "MySQLi"
  database.chatbot.DBPrefix: ""
  database.chatbot.port: "3306"
  database.crm.hostname: "mysql-main-instances"
  database.crm.database: "pim_crm"
  database.crm.username: "dbmasteruser"
  database.crm.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.crm.DBDriver: "MySQLi"
  database.crm.DBPrefix: ""
  database.crm.port: "3306"
  aws.s3.accesskey: "CHANGE_ME_PROD_AWS_ACCESSKEY"
  aws.s3.secretkey: "CHANGE_ME_PROD_AWS_SECRETKEY"
  aws.s3.region: "ap-southeast-1"
  aws.s3.bucket: "CHANGE_ME_PROD_AWS_BUCKET"
  aws.s3.uploaddir: "CHANGE_ME_PROD_AWS_UPLOAD_DIR"
  magento.env: "production"
  magento.server.production: "CHANGE_ME_PROD_MAGENTO_SERVER_PROD"
  magento.token.production: "CHANGE_ME_PROD_MAGENTO_TOKEN_PROD"
  magento.server.staging: "CHANGE_ME_PROD_MAGENTO_SERVER_STAGING"
  magento.token.staging: "CHANGE_ME_PROD_MAGENTO_TOKEN_STAGING"
  magento.oauth_consumer_key: "CHANGE_ME_PROD_MAGENTO_OAUTH_KEY"
  email.smtp.username: "CHANGE_ME_PROD_EMAIL_SMTP_USERNAME"
  email.smtp.password: "CHANGE_ME_PROD_EMAIL_SMTP_PASSWORD"
  email.from_address: "CHANGE_ME_PROD_EMAIL_FROM_ADDRESS"
  email.from_name: "CHANGE_ME_PROD_EMAIL_FROM_NAME"
  email.admin_cc: "CHANGE_ME_PROD_EMAIL_ADMIN_CC"
  encryption.key: "CHANGE_ME_PROD_ENCRYPTION_KEY"
  encryption.salt: "CHANGE_ME_PROD_ENCRYPTION_SALT"
  deployer.secretkey: "CHANGE_ME_PROD_DEPLOYER_SECRETKEY"
