kind: Secret
apiVersion: v1
metadata:
  name: magento-composer-auth
  namespace: magento
type: Opaque
stringData:
  auth.json: |
    {
      "http-basic": {
        "repo.magento.com": {
          "username": "YOUR_PUBLIC_KEY",
          "password": "YOUR_PRIVATE_KEY"
        }
      }
    }
