apiVersion: v1
kind: Service
metadata:
  name: percona-mysql-nodeport
  namespace: database
  labels:
    app: percona-mysql
spec:
  type: NodePort
  selector:
    app: percona-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30006
      protocol: TCP