apiVersion: v1
kind: Service
metadata:
  name: postgres-main-nodeport
  namespace: database
  labels:
    app: postgres-main
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgres-main
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30002
      protocol: TCP