apiVersion: v1
kind: Secret
metadata:
  name: pim-bucket-upload-secret
  namespace: pim-bucket-upload
  labels:
    app.kubernetes.io/name: pim-bucket-upload
    app.kubernetes.io/instance: pim-bucket-upload-prod
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  CI_ENVIRONMENT: "production"
  aws.s3.accesskey: "CHANGE_ME_PROD_AWS_ACCESSKEY"
  aws.s3.secretkey: "CHANGE_ME_PROD_AWS_SECRETKEY"
  aws.s3.region: "ap-southeast-1"
  aws.s3.bucket: "CHANGE_ME_PROD_AWS_BUCKET"
  aws.s3.url: "CHANGE_ME_PROD_AWS_URL"
  database.default.hostname: "mysql-main-instances"
  database.default.database: "electgo_bucket"
  database.default.username: "dbmasteruser"
  database.default.password: "}LtL:VA1*{7L3_rIs)Q?v?E4mwk?W7:J"
  database.default.DBDriver: "MySQLi"
  database.default.DBPrefix: ""
  database.default.port: "3306"
