apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pim-chatbot-prod
  namespace: argocd
spec:
  project: product
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: pim-chatbot-env
      namespace: pim-chatbot
      jsonPointers:
        - /data
        - /stringData
    - group: apps
      kind: Deployment
      name: pim-chatbot
      namespace: pim-chatbot
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1env
  source:
    repoURL: https://github.com/electgo/pim-chatbot
    targetRevision: main
    path: deployments/helm
    helm:
      releaseName: pim-chatbot
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: secret.create
          value: "false"
  destination:
    name: production
    namespace: pim-chatbot
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
