apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pim-bucket-upload
  namespace: argocd
spec:
  project: product
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: pim-bucket-upload-secret
      namespace: pim-bucket-upload
      jsonPointers:
        - /data
        - /stringData
  source:
    repoURL: https://github.com/electgo/pim-bucket-upload.git
    targetRevision: develop
    path: helm/pim-bucket-upload
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    name: development
    namespace: pim-bucket-upload
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
