apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ElectGo2026Mysql"
  MYSQL_DATABASE: "matomo"
  MYSQL_USER: "matomo"
  MYSQL_PASSWORD: "ElectGo2026Mysql"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "ElectGo2026Postgres"
  POSTGRES_DB: "openproject"
