apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: electgo-be-report-dev
  namespace: argocd
spec:
  project: marketplace
  source:
    repoURL: https://github.com/electgo/electgo-be-report
    targetRevision: develop
    path: helm/electgo-be-report
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: namespace.name
          value: electgo-be-report
        - name: replicaCount
          value: "1"
        - name: env.config.NODE_ENV
          value: development
        - name: secret.create
          value: "true"
        - name: imageCredentials.create
          value: "false"
        - name: env.secret.MONGODB_URI
          value: "mongodb://sharedops:__REDACTED_SHAREDOPS_PASSWORD__@mongodb.database.svc.cluster.local:27017/electgo?authSource=admin"
        - name: env.secret.POSTGRES_DB
          value: "electgo_report"
        - name: env.secret.POSTGRES_HOST
          value: "postgresql.database.svc.cluster.local"
        - name: env.secret.POSTGRES_PASSWORD
          value: "__REDACTED_SHAREDOPS_PASSWORD__"
        - name: env.secret.POSTGRES_USER
          value: "sharedops"
  destination:
    server: https://10.20.17.100:6443
    namespace: electgo-be-report
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
