apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-dev
  namespace: argocd
spec:
  project: management
  source:
    path: infra/databases/development
    repoURL: https://github.com/electgo/manifest.git
    targetRevision: main
    directory:
      include: '*.yaml'
  destination:
    name: development
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/revision
        - /status
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'
        - '.spec.template.spec.initContainers[]?.imagePullPolicy'
