apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-local
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://project-zot.github.io/helm-charts
      chart: zot
      targetRevision: 0.1.113
      helm:
        releaseName: zot-registry
        valueFiles:
          - $values/argo/zot-local/values-local.yaml
    - repoURL: https://github.com/electgo/manifest
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: electgo-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
