apiVersion: v1
kind: Secret
metadata:
  name: product-ai-enrich-secret
  namespace: product-ai-enrich
  labels:
    app.kubernetes.io/name: product-ai-enrich
    app.kubernetes.io/instance: product-ai-enrich-prod
    app.kubernetes.io/managed-by: argocd-manual
type: Opaque
stringData:
  DB_HOST: "mysql-main-instances"
  DB_PORT: "3306"
  DB_USER: "dbmasteruser"
  DB_PASSWORD: "CHANGE_ME_PROD_DB_PASSWORD"
  DB_DATABASE: "product_recommendation"
  SERVER_PORT: "8004"
  GPT_MODEL: "gpt-4.1-mini"
  GPT_KEY: "CHANGE_ME_PROD_GPT_KEY"
  ENHANCER_ID: "CHANGE_ME_PROD_ENHANCER_ID"
  CRAWLER_ID: "CHANGE_ME_PROD_CRAWLER_ID"
  DB_SSL: "true"
  DB_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
