apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chatbot
  namespace: argocd
spec:
  description: All chatbot services across development and production
  sourceRepos:
    - https://github.com/electgo/etools-chatbot-fe.git
    - https://github.com/electgo/etools-chatbot-be.git
  destinations:
    - name: development
      namespace: etools-chatbot-*
    - name: production
      namespace: etools-chatbot-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
