apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Management cluster applications + dev/prod shared infra (databases, observability, etc.)
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - name: development
    namespace: database
  - name: development
    namespace: nfs-subdir
  sourceRepos:
  - https://github.com/electgo/manifest.git
  - https://github.com/electgo/manifest
  - https://kubernetes-sigs.github.io/external-dns/
  - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  - https://grafana.github.io/helm-charts
  - https://prometheus-community.github.io/helm-charts
  - https://releases.rancher.com/server-charts/alpha
  orphanedResources:
    warn: false
