apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform control plane and shared services across clusters
  sourceRepos:
    - https://github.com/electgo/manifest
    - https://github.com/electgo/manifest.git
    - ghcr.io/actions/actions-runner-controller-charts
    - https://kubernetes-sigs.github.io/external-dns/
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    - https://releases.rancher.com/server-charts/alpha
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cattle-system
    - server: https://kubernetes.default.svc
      namespace: database
    - server: https://kubernetes.default.svc
      namespace: external-dns
    - server: https://kubernetes.default.svc
      namespace: matomo
    - server: https://kubernetes.default.svc
      namespace: openproject
    - server: https://kubernetes.default.svc
      namespace: zitadel
    - server: https://kubernetes.default.svc
      namespace: zot
    - name: development
      namespace: argocd
    - name: development
      namespace: database
    - name: development
      namespace: nfs-subdir
    - name: production
      namespace: argocd
    - name: production
      namespace: matomo
    - name: development
      namespace: matomo
    - name: production
      namespace: arc-systems
    - name: production
      namespace: arc-runners
    - name: development
      namespace: arc-systems
    - name: development
      namespace: arc-runners
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
