apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      managedFieldsManagers:
        - kyverno
  source:
    repoURL: https://github.com/electgo/manifest.git
    targetRevision: main
    path: k8s/production/observability/kyverno
  destination:
    name: production
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
