apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-prod
  namespace: argocd
spec:
  destination:
    name: production
    namespace: monitoring
  project: observability
  source:
    chart: promtail
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki-gateway.monitoring.svc/loki/api/v1/push
              tenant_id: ""
          snippets:
            pipelineStages:
              - cri: {}
              - match:
                  selector: '{namespace=~".+"}'
                  stages:
                    - labels:
                        level:
            extraRelabelConfigs:
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                target_label: app
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
                target_label: component
        serviceMonitor:
          enabled: true
          labels:
            release: kps
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        tolerations:
          - operator: Exists
        priorityClassName: system-node-critical
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.6
